FROM ubuntu:xenial
MAINTAINER  Satish Kumar <satishrawat92@gmail.com>

#get updates/prerequisites and install JDK 

RUN apt-get update && apt-get install -y git wget curl jq unzip && apt-get -y install software-properties-common && add-apt-repository -y ppa:webupd8team/java && echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && apt install openjdk-8-jdk -y 

##install jdk8
RUN JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && PATH=${M2_HOME}/bin:${PATH} && M2_HOME=/opt/maven


#install maven#
WORKDIR /opt/
RUN wget http://mirror.olnevhost.net/pub/apache/maven/binaries/apache-maven-3.2.2-bin.tar.gz && tar -xvzf apache-maven-3.2.2-bin.tar.gz && rm apache-maven-3.2.2-bin.tar.gz && mv apache-maven-3.2.2 maven



##Install terraform

RUN wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip && unzip terraform_0.12.8_linux_amd64.zip && rm terraform_0.12.8_linux_amd64.zip && mv terraform /usr/local/bin/

##Install helm#
RUN wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz && tar -xvf helm-v2.14.3-linux-amd64.tar.gz && rm helm-v2.14.3-linux-amd64.tar.gz && mv linux-amd64/* /usr/local/bin/




##Install Golang
RUN wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz && tar -xvf go1.13.linux-amd64.tar.gz && rm go1.13.linux-amd64.tar.gz && mv go /usr/local && mkdir /opt/goproject 
RUN GOROOT=/usr/local/go && GOPATH=/opt/goproject && PATH=$GOPATH/bin:$GOROOT/bin:$PATH

##install gradle
RUN wget https://downloads.gradle-dn.com/distributions/gradle-5.6.2-all.zip && mkdir -p /opt/gradle && unzip -d /opt/gradle gradle-5.6.2-all.zip 
RUN PATH=$PATH:/opt/gradle/gradle-5.6.2/bin


##install kubectl ##
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl


##install gcloud
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

RUN rm -rf /var/lib/apt/lists/*


