FROM jenkins/slave:latest-jdk11

MAINTAINER  Naveen <naveen@gmail.com>

#get updates/prerequisites and install JDK 

USER root
RUN apt-get update && apt-get install -y git wget curl jq unzip 
# get maven 3.3.9
RUN wget --no-verbose -O /tmp/apache-maven-3.3.9.tar.gz http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz

# verify checksum
RUN echo "516923b3955b6035ba6b0a5b031fbd8b /tmp/apache-maven-3.3.9.tar.gz" | md5sum -c

# install maven
RUN tar xzf /tmp/apache-maven-3.3.9.tar.gz -C /opt/ && \
    ln -s /opt/apache-maven-3.3.9 /opt/maven && \
    ln -s /opt/maven/bin/mvn /usr/local/bin && \
    rm -f /tmp/apache-maven-3.3.9.tar.gz
ENV MAVEN_HOME /opt/maven
##Install terraform

RUN wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip && unzip terraform_0.12.8_linux_amd64.zip && rm terraform_0.12.8_linux_amd64.zip && mv terraform /usr/local/bin/

##Install helm#
RUN wget https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz && tar -xvf helm-v2.14.3-linux-amd64.tar.gz && rm helm-v2.14.3-linux-amd64.tar.gz && mv linux-amd64/* /usr/local/bin/
##Install Golang
RUN wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz && tar -xvf go1.13.linux-amd64.tar.gz && rm go1.13.linux-amd64.tar.gz && mv go /usr/local && mkdir /opt/goproject
ENV GOROOT=/usr/local/go
ENV GOPATH=/opt/goproject
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

##install gradle
RUN wget https://downloads.gradle-dn.com/distributions/gradle-5.6.2-all.zip && mkdir -p /opt/gradle && unzip -d /opt/gradle gradle-5.6.2-all.zip
ENV PATH=$PATH:/opt/gradle/gradle-5.6.2/bin
##install kubectl ##
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
##install gcloud
RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin
CMD tail -f /dev/null
